### Executa apenas em push

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'src/**' ### CRIAR ARQUIVOS AQUI PARA DISPARAR O PIPELINE
      - 'README.md' ### QUANDO O ARQUIVO FOR EDITADO

jobs:
  push-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Info do push
        run: |
          echo "Workflow disparado por PUSH"
          echo "Commit: ${{ github.sha }}"
          echo "Autor: ${{ github.actor }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "Repositório: ${{ github.repository }}"
      
      - name: Listar arquivos modificados
        run: |
          echo "Arquivo no repositório:"
          ls -la